/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainUI;

import App.App;
import User.User;
import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import javax.swing.JOptionPane;

/**
 * Esta clase es por donde se gestionan los usuarios (interfaz)
 *
 * @author Jesus
 * @version 4/6.2023
 */
public class LoginUI extends javax.swing.JFrame {

    int mouseX, mouseY;
    App app;

    /**
     * Constructor
     */
    public LoginUI() {
        //Configuraciones de la interfaz
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        panelLogin = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        exitBot = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        singUp = new javax.swing.JLabel();

        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(380, 420));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jPanel2.setBackground(new java.awt.Color(59, 89, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Klavika Md", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("facebook");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 210, 70));

        Username.setBackground(new java.awt.Color(255, 255, 255));
        Username.setFont(new java.awt.Font("Klavika Lt", 0, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(153, 153, 153));
        Username.setText("Ingrese el usuario");
        Username.setBorder(null);
        Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsernameMousePressed(evt);
            }
        });
        jPanel2.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 320, 40));

        Password.setBackground(new java.awt.Color(255, 255, 255));
        Password.setForeground(new java.awt.Color(153, 153, 153));
        Password.setText("**********");
        Password.setBorder(null);
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordMousePressed(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 320, 40));

        panelLogin.setBackground(new java.awt.Color(33, 56, 115));
        panelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));

        Login.setBackground(new java.awt.Color(0, 0, 0));
        Login.setFont(new java.awt.Font("Klavika Lt", 0, 14)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("Entrar");
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 120, 40));

        jPanel4.setBackground(new java.awt.Color(59, 89, 153));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        exitBot.setBackground(new java.awt.Color(59, 89, 153));

        exit.setFont(new java.awt.Font("Klavika Bd", 0, 24)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("X");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBotLayout = new javax.swing.GroupLayout(exitBot);
        exitBot.setLayout(exitBotLayout);
        exitBotLayout.setHorizontalGroup(
            exitBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );
        exitBotLayout.setVerticalGroup(
            exitBotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBotLayout.createSequentialGroup()
                .addComponent(exit)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(exitBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 336, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" ¿Olivaste la contraseña  ?");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 160, -1));

        jPanel3.setBackground(new java.awt.Color(33, 56, 115));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        singUp.setFont(new java.awt.Font("Klavika Lt", 0, 14)); // NOI18N
        singUp.setForeground(new java.awt.Color(255, 255, 255));
        singUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        singUp.setText("Registrarse");
        singUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        singUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                singUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                singUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                singUpMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(singUp, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(singUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 110, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   /**
 * Metodo que te permite volver a asignar la variable app, para poder bascular en las otras interfacez
 *
 * @param app contiene todo los datos que se corren en el programa 
 * @version 4/6.2023
 */

    public void setApp(App app) {
        this.app = app;
    }
            //Configuraciones de la interfaz 
    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        // TODO add your handling code here:
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel4MousePressed
        //Configuraciones de la interfaz para que puedan mover la pestaña
    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_jPanel4MouseDragged
        //Configuraciones de la interfaz para cerrar la pestaña
    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_exitMouseClicked
        //Configuraciones de la interfaz para cambiar color 
    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
        // TODO add your handling code here:
        exitBot.setBackground(Color.red);

    }//GEN-LAST:event_exitMouseEntered
        //Configuraciones de la interfaz para cambiar color 
    private void LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseEntered
        // TODO add your handling code here:
        panelLogin.setBackground(new Color(67, 104, 201));


    }//GEN-LAST:event_LoginMouseEntered
        //Configuraciones de la interfaz para cambiar color 
    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
        exitBot.setBackground(new Color(59, 89, 153));
    }//GEN-LAST:event_exitMouseExited
        //Configuraciones de la interfaz para cambiar color 
    private void LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseExited
        // TODO add your handling code here:
        panelLogin.setBackground(new Color(33, 56, 115));
    }//GEN-LAST:event_LoginMouseExited
        //Configuraciones de la interfaz para estetica
    private void UsernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMousePressed
        // TODO add your handling code here:

        if (Username.getText().equals("Ingrese el usuario")) {
            Username.setText("");
            Username.setForeground(Color.BLACK);
        }
        if (String.valueOf(Password.getPassword()).isEmpty()) {
            Password.setText("**********");
            Password.setForeground(Color.gray);
        }
    }//GEN-LAST:event_UsernameMousePressed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed
        //Configuraciones de la interfaz para estetica
    private void PasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMousePressed
        // TODO add your handling code here:
        if (Username.getText().isEmpty()) {
            Username.setText("Ingrese el usuario");
            Username.setForeground(Color.gray);
        }
        if (String.valueOf(Password.getPassword()).equals("**********")) {
            Password.setText("");
            Password.setForeground(Color.BLACK);
        }

    }//GEN-LAST:event_PasswordMousePressed

    private void UsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_UsernameMouseClicked

    private void PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_PasswordMouseClicked
    //Boton que te permite iniciar sesion con un usuarios
    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        // TODO add your handling code here:
        if (this.app.userOld(Username.getText(), String.valueOf(Password.getPassword())) == true) {
            this.app.getUser(Username.getText(), String.valueOf(Password.getPassword())); //Valida que exista ese usuario con esa contrase;a
            MenuUI menu = new MenuUI(); //Abre la clase donde se hace todas las modificaciones del grafo
            User user = this.app.getUser(Username.getText(), String.valueOf(Password.getPassword())); //Devuelve el usuario 
            menu.getAppUser(app, user); //Pasa los parametros user para que puedan trabajar con ellos
            menu.escribirUser(app.getList()); //Escribe la lista de usuarios para que puedas ver los posibles arcos que puedes hacer
            this.setVisible(false);
            menu.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Contraseña/Usuario invalido. ");
        }

    }//GEN-LAST:event_LoginMouseClicked
        //FIn del metodo


        //Configuraciones de la interfaz para estetica
    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        Font subrayado = new Font("Arial", TextAttribute.UNDERLINE_ON, 12);
        jLabel2.setFont(subrayado);
        jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_jLabel2MouseEntered
        //Configuraciones de la interfaz para estetica
    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        Font fuente = new Font("Arial", Font.PLAIN, 12);
        jLabel2.setFont(fuente);
        jLabel2.setForeground(Color.white);


    }//GEN-LAST:event_jLabel2MouseExited
        //Configuraciones de la interfaz para estetica
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Recuerde que la contrasaña solamente puede contener numeros (max 3 nums)");
    }//GEN-LAST:event_jLabel2MouseClicked
    //Cuando le dan clikc a registrarse te abre la pesta;a de iniciar sesion
    private void singUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singUpMouseClicked
        // TODO add your handling code here:
        SignUpUI u=new SignUpUI(); //Pesta;a de iniciar sesion 
        u.setApp(app);
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_singUpMouseClicked
    //FIn del metodo    

    //Configuraciones de la interfaz para estetica
    private void singUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singUpMouseEntered
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(67, 104, 201));
    }//GEN-LAST:event_singUpMouseEntered
        //Configuraciones de la interfaz para estetica
    private void singUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_singUpMouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(33, 56, 115));
    }//GEN-LAST:event_singUpMouseExited
        //Configuraciones de la interfaz para estetica
    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
         jPanel3.setBackground(new Color(67, 104, 201));
    }//GEN-LAST:event_jPanel3MouseEntered
        //Configuraciones de la interfaz para estetica
    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(33, 56, 115));
    }//GEN-LAST:event_jPanel3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Login;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel exitBot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JLabel singUp;
    // End of variables declaration//GEN-END:variables
}
