/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MainUI;

import App.App;
import Lista.Lista;
import User.User;
import Funciones.Funciones;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.TextArea;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.graphstream.ui.view.Viewer;

/**
 * En esta clase se hacen las operaciones basicas del grafo: mostrar, agregar y eliminar arcl (Interfaz)
 *
 * @author Jesus
 * @version 4/6.2023
 */
public class MenuUI extends javax.swing.JFrame {

    App app;
    User user;
    private final Dimension minimunUI = new Dimension(596, 560);
    private final Dimension maximunUI = new Dimension(596, 560);

    /**
     * Constructor
     */
    public MenuUI() {
        //Configuaraciones de la pestaña
        initComponents();
        this.app = null;
        this.user = null;
        this.setLocationRelativeTo(null);
        this.setMinimumSize(this.minimunUI);
        this.setMaximumSize(this.maximunUI);
        this.setResizable(false);

    }
    //Asignar el usuarios y la app para saber que valores estamos trabajando.
    public void getAppUser(App app, User user) {
        this.app = app;
        this.user = user;
        tagUser.setText(user.getName()); // Colocas el usuario correspondiente para que el usuario pueda ver en que user se encuentra
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bottonExit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tagUser = new javax.swing.JLabel();
        bottonAgregar = new javax.swing.JPanel();
        añadirUsu = new javax.swing.JLabel();
        bottonElimi = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bottonMostr1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListUser = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(596, 560));
        setMinimumSize(new java.awt.Dimension(596, 560));
        setPreferredSize(new java.awt.Dimension(596, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(59, 89, 153));

        jLabel2.setFont(new java.awt.Font("Klavika Md", 0, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("f");
        jLabel2.setToolTipText("");

        bottonExit.setBackground(new java.awt.Color(59, 89, 153));
        bottonExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bottonExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bottonExitMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cerrar sesion");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout bottonExitLayout = new javax.swing.GroupLayout(bottonExit);
        bottonExit.setLayout(bottonExitLayout);
        bottonExitLayout.setHorizontalGroup(
            bottonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottonExitLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        bottonExitLayout.setVerticalGroup(
            bottonExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottonExitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(332, 332, 332)
                .addComponent(bottonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bottonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Perfil");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 6, -1, -1));

        tagUser.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tagUser.setForeground(new java.awt.Color(0, 0, 0));
        tagUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel3.add(tagUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 30));

        bottonAgregar.setBackground(new java.awt.Color(255, 255, 255));
        bottonAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bottonAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bottonAgregarMouseExited(evt);
            }
        });

        añadirUsu.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        añadirUsu.setForeground(new java.awt.Color(0, 0, 0));
        añadirUsu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        añadirUsu.setText("Agregar Amigos");
        añadirUsu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        añadirUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añadirUsuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                añadirUsuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                añadirUsuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bottonAgregarLayout = new javax.swing.GroupLayout(bottonAgregar);
        bottonAgregar.setLayout(bottonAgregarLayout);
        bottonAgregarLayout.setHorizontalGroup(
            bottonAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottonAgregarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(añadirUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        bottonAgregarLayout.setVerticalGroup(
            bottonAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottonAgregarLayout.createSequentialGroup()
                .addComponent(añadirUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.add(bottonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 180, 40));

        bottonElimi.setBackground(new java.awt.Color(255, 255, 255));
        bottonElimi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bottonElimiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bottonElimiMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Eliminar Amigos");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout bottonElimiLayout = new javax.swing.GroupLayout(bottonElimi);
        bottonElimi.setLayout(bottonElimiLayout);
        bottonElimiLayout.setHorizontalGroup(
            bottonElimiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottonElimiLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        bottonElimiLayout.setVerticalGroup(
            bottonElimiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottonElimiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(bottonElimi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, 40));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 74, 180, 20));

        bottonMostr1.setBackground(new java.awt.Color(255, 255, 255));
        bottonMostr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bottonMostr1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bottonMostr1MouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Mostrar Amigos");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout bottonMostr1Layout = new javax.swing.GroupLayout(bottonMostr1);
        bottonMostr1.setLayout(bottonMostr1Layout);
        bottonMostr1Layout.setHorizontalGroup(
            bottonMostr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottonMostr1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        bottonMostr1Layout.setVerticalGroup(
            bottonMostr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottonMostr1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(22, 22, 22))
        );

        jPanel3.add(bottonMostr1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 180, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 180, 480));

        ListUser.setEditable(false);
        ListUser.setBackground(new java.awt.Color(255, 255, 255));
        ListUser.setColumns(20);
        ListUser.setRows(5);
        jScrollPane1.setViewportView(ListUser);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 73, 420, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Configuaraciones de la estetica de la interfaz
    private void bottonAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonAgregarMouseEntered
        // TODO add your handling code here:
        this.bottonAgregar.setBackground(Color.lightGray);
    }//GEN-LAST:event_bottonAgregarMouseEntered
    //Configuaraciones de la estetica de la interfaz
    private void bottonElimiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonElimiMouseEntered
        // TODO add your handling code here:
        this.bottonElimi.setBackground(Color.lightGray);
    }//GEN-LAST:event_bottonElimiMouseEntered
    //Configuaraciones de la estetica de la interfaz
    private void bottonElimiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonElimiMouseExited
        // TODO add your handling code here:
        this.bottonElimi.setBackground(Color.white);
    }//GEN-LAST:event_bottonElimiMouseExited
    //Configuaraciones de la estetica de la interfaz
    private void bottonAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonAgregarMouseExited
        // TODO add your handling code here:
        this.bottonAgregar.setBackground(Color.white);
    }//GEN-LAST:event_bottonAgregarMouseExited
    //Configuaraciones de la estetica de la interfaz
    private void bottonExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonExitMouseEntered
        // TODO add your handling code here:d);
        bottonExit.setBackground(Color.red);
    }//GEN-LAST:event_bottonExitMouseEntered
    //Configuaraciones de la estetica de la interfaz
    private void bottonExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonExitMouseExited
        // TODO add your handling code here:

        bottonExit.setBackground(new Color(59, 89, 153));
    }//GEN-LAST:event_bottonExitMouseExited
    //Configuaraciones de la estetica de la interfaz
    private void bottonMostr1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonMostr1MouseEntered
        // TODO add your handling code here:
        this.bottonMostr1.setBackground(Color.lightGray);
    }//GEN-LAST:event_bottonMostr1MouseEntered
    //Configuaraciones de la estetica de la interfaz
    private void bottonMostr1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bottonMostr1MouseExited
        // TODO add your handling code here:
        this.bottonMostr1.setBackground(Color.white);

    }//GEN-LAST:event_bottonMostr1MouseExited
    //Al clickear añadir usuarios dispondras de inputs para que puedas completar la funcion
    private void añadirUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirUsuMouseClicked
        // TODO add your handling code here:
        while (true) {
            int id = Funciones.stringToInt(JOptionPane.showInputDialog(null, "Ingresa el id del usuario.")); //Codigo del usuario
            int value = Funciones.stringToInt(JOptionPane.showInputDialog(null, "El tiempo de amistad (Valor) ")); //El valor del arco
            if (id != 0 && value != 0 && value < 20) { //Validacion ya que es imposible tener 100 años/meses de amistad con alguien
                if (!app.getList().search(user.getId())) {  //Se agrega a la lista de usuarios, por si el usuario es nuevo y proviene de iniciar sesion
                    app.getList().addLast(user);    //o no tenia ningun arco en su vertice
                }
                app.edgeUser(user.getId(), id, value); //Se pasan los parametros id del usuario, el id del destino y el valor del enlace
                break;
            } else {
                JOptionPane.showMessageDialog(null, "Algun valor esta errado");
            }
        }


    }//GEN-LAST:event_añadirUsuMouseClicked
    //FIn del metodo

    //Configuaraciones de la estetica de la interfaz
    private void añadirUsuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirUsuMouseEntered
        // TODO add your handling code here:
        this.bottonAgregar.setBackground(Color.lightGray);
    }//GEN-LAST:event_añadirUsuMouseEntered
     //Configuaraciones de la estetica de la interfaz
    private void añadirUsuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añadirUsuMouseExited
        // TODO add your handling code here:
        this.bottonAgregar.setBackground(Color.white);
    }//GEN-LAST:event_añadirUsuMouseExited
     //Configuaraciones de la estetica de la interfaz
    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        this.bottonElimi.setBackground(Color.lightGray);
    }//GEN-LAST:event_jLabel6MouseEntered
     //Configuaraciones de la estetica de la interfaz
    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        this.bottonElimi.setBackground(Color.white);
    }//GEN-LAST:event_jLabel6MouseExited
    //Al clickear eliminar te pide el id del usuarios que deseas eliminar de tus enlaces, revisa que sea cierto y lo elimina
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        while (true) {
            int id = Funciones.stringToInt(JOptionPane.showInputDialog(null, "Ingresa el id del usuario.")); //Validacion del String para entero
            if (id != 0) {
                if (app.getList().search(id)) { //Busca el valor del id pedido en la lista de usuarios
                    if (app.getList().search(user.getId()) != true) { //Si el usuario no se encuentra en la lista de usuarios es porque esta vacio
                        JOptionPane.showMessageDialog(null, "No puedes eliminar si esta vacio");
                        break;
                    }
                    app.eliminarArco(user.getId(), id); //Pasas los parametros y llamas la funcion eliminar arco
                    break;
                }
            } else {
                JOptionPane.showMessageDialog(null, "Algun valor esta errado");
            }
        }

    }//GEN-LAST:event_jLabel6MouseClicked
     //FIn del metodo   

     //Al clickear cerrar sesion, pregunta si el usuario esta seguro y te manda al incio del todo
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        String option = JOptionPane.showInputDialog("Esta seguro? (Si)(No)").toLowerCase();
        if ("si".equals(option)) {
            this.setVisible(false);
            MainUI main = new MainUI();
            main.setApp(app);
            main.setVisible(true);

        }
    }//GEN-LAST:event_jLabel5MouseClicked
    //FIn del metodo
    
    //Al clickear mostrar puedes seleccionar que quieres ver y dependiendo de tu eleccion te lo muestra
    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here
        String option = JOptionPane.showInputDialog("Que deseas ver?(1.El grafo)(2.Los puentes)");
        switch (option) {
            case "1":
                mostrarGraf(); //Llama la funcion mostrar grafo
                break;
            case "2":
                mostrarPuent(); // Llama la funcion mostrar puentes y los escribe
                break;
            default:
                JOptionPane.showInternalMessageDialog(null, "Error");

        }

    }//GEN-LAST:event_jLabel7MouseClicked
        //FIn del metodo   

//Metodo te muestra todos los arcos que son puentes y te los muestra
    public void mostrarPuent() {
        app.puentes();

    }//FIn del metodo
    
    
    //Metodo que te pregunta que deseas visualizar y dependiendo de tu eleccion, te abre una pestaña con esa informacion
    public void mostrarGraf() {
        JFrame j = new JFrame(); //Creas una nueva pestaña para poder pasar los valores que traeremos
        TextArea a = new TextArea();
        a.setEditable(false);
        j.setSize(400, 300);
        j.setLocationRelativeTo(null);
        j.add(a);
        String option = JOptionPane.showInputDialog("1.Visualmente\n2.DFS\n3.BFS");
        switch (option) {
            case "1":
                Nose n = new Nose(); 
                n.mostrarGrafo(app); //Muestras una pestaña donde puedes ver el grafo 
                break;
            case "2":
                a.setText(app.mostrarGrafoDFS()); //Pasa el recorrido de los grafos por DFS
                j.setVisible(true);
                j.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                break;
            case "3":
                a.setText(app.mostrarGrafoBFS());//Pasa el recorrido de los grafos por BFS
                j.setVisible(true);
                j.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                break;
            default:
                JOptionPane.showInternalMessageDialog(null, "Error");

        }
    }//FIn del metodo
         //Configuaraciones de la estetica de la interfaz
    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
        bottonExit.setBackground(Color.red);
    }//GEN-LAST:event_jLabel5MouseEntered
     //Configuaraciones de la estetica de la interfaz
    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        // TODO add your handling code here:
        bottonExit.setBackground(new Color(59, 89, 153));
    }//GEN-LAST:event_jLabel5MouseExited
    //Configuaraciones de la estetica de la interfaz
    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        this.bottonMostr1.setBackground(Color.lightGray);
    }//GEN-LAST:event_jLabel7MouseEntered
    //Configuaraciones de la estetica de la interfaz
    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        this.bottonMostr1.setBackground(Color.white);
    }//GEN-LAST:event_jLabel7MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUI().setVisible(true);
            }
        });
    }
/**

     * Método que escribe la lista de usuarios en un text y los coloca en un textArea, para se logre visualizar en la interfaz

     * 

     */
    public void escribirUser(Lista x) {
        String text = "\n\n     Lista de Usuarios\n\n";
        for (int i = 0; i < x.size(); i++) {
            User aux = (User) x.getValuePosition(i);
            if (aux != this.user) {
                text += (aux.getId()) + ".  " + aux.getName() + "\n";

            }
        }
        ListUser.setText(text);
    }//FIn del metodo
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ListUser;
    private javax.swing.JLabel añadirUsu;
    private javax.swing.JPanel bottonAgregar;
    private javax.swing.JPanel bottonElimi;
    private javax.swing.JPanel bottonExit;
    private javax.swing.JPanel bottonMostr1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel tagUser;
    // End of variables declaration//GEN-END:variables
}
